### ISSUE TITLE
如果我想做列表 修改内容的编辑 怎么获取每一个列表里面的相关文本呢

### ISSUE THREAD

**Issue by YangYuChan** [SilentTiger/vue-ueditor#13]
![tim 20170729154731](https://user-images.githubusercontent.com/17611829/28743185-11fcd0c0-7476-11e7-8f56-723c16f5d0ee.png)

我现在用这种方式，但是获取的都只是第一次点击的时候相对应的内容， 后续的再点击其他的，内容不会改变，我想获取每一次点击的时候，相关的内容

**Comment by SilentTiger** [comment]
你的问题和vue-ueditor没什么关系，应该查一下UEditor的文档。
