### ISSUE TITLE
install之后 .babelrc文件里面报transform-runtime,state-2这个错

### ISSUE THREAD

**Issue by LeeRayno** [SilentTiger/vue-ueditor#2]
install之后 .babelrc文件里面报transform-runtime,state-2这个错。把这两项配置删了就不报错了。但是别人安装之后也会包这个错。这个要怎么解决了。

**Comment by SilentTiger** [comment]
这个组件应该不会对 .babelrc 产生影响吧，我下周再看看

**Comment by SilentTiger** [comment]
我好像没有重现你说的问题

**Comment by chendawei33** [comment]
出现了楼主一样的问题，安装transform-runtime后还是报错
