### ISSUE TITLE
Couldn't find preset "es2015" relative to directory

### ISSUE THREAD

**Issue by FiumeHoo** [SilentTiger/vue-ueditor#23]
Module build failed: Error: Couldn't find preset "es2015" relative to directory

**Comment by iamjoel** [comment]
遇到了一样的问题，我用下面的方法解决了：
```
npm install --save babel-preset-es2015
```
具体见 https://stackoverflow.com/questions/34819473/error-couldnt-find-preset-es2015-relative-to-directory-users-username
