### ISSUE TITLE
支持v-model双向数据绑定版本，请移步https://github.com/HaoChuan9421/vue-ueditor-wrap

### ISSUE THREAD

**Issue by ghost** [SilentTiger/vue-ueditor#27]
https://github.com/HaoChuan9421/vue-ueditor-wrap
![timg](https://user-images.githubusercontent.com/28668354/41366659-68005d8a-6f6f-11e8-9c3f-24691fa37613.jpeg)

**Comment by SilentTiger** [comment]
这个之前说过很多次了，ueditor 的 contentchange 事件触发有问题，你应该也知道，所以暂时不打算实现双向绑定，谢谢
