### ISSUE TITLE
后台配置项返回格式出错，上传功能将不能正常使用！

### ISSUE THREAD

**Issue by LeeRayno** [SilentTiger/vue-ueditor#3]
关于这项报错。我百度了下。说把chongqing 改成Chongqing还是不行。你有遇到这个问题吗。还是说没有后台导致的。

**Comment by SilentTiger** [comment]
请参考UEditor 的文档 [http://fex.baidu.com/ueditor/#server-deploy](http://fex.baidu.com/ueditor/#server-deploy)

**Comment by Sweet-KK** [comment]
研究一整天了,用nodejs不知道怎么配,找的文章都试过了,该改的改,自己都觉得逻辑上没问题的,可就是一直显示请求后台配置项http错误，上传功能将不能正常使用！
