### ISSUE TITLE
能否发布一个sample？

### ISSUE THREAD

**Issue by chinavane** [SilentTiger/vue-ueditor#5]
获取数据的方法如何处理？

**Comment by SilentTiger** [comment]
你可以把代码clone到本地，cnpm i 安装依赖项，然后执行 npm run dev
然后你应该可以看到一个页面，就是我写的demo，这个demo的代码在app.vue里面
当然，这个demo主要是演示 api 的用法，至于如何引用到你的项目里面应该还是有少许不同的。
