### ISSUE TITLE
contentChange事件无法监控到图片上传等异步处理后的数据变更

### ISSUE THREAD

**Issue by ccfish86** [SilentTiger/vue-ueditor#7]
无法监控到图片上传后的真实URL。差不多得到的是下图这样的数据，
![image](https://cloud.githubusercontent.com/assets/15622514/24836128/3ef0f264-1d46-11e7-934d-0ea7e36ced2f.png)

**Comment by SilentTiger** [comment]
1、我也发现 contentChange 的事件触发不是很可靠，所以我推荐在你需要读取内容的时候用 getContent 手动获取
2、如果你确认这是一个功能bug，可以去 Ueditor 官网提 issue

**Comment by tyua07** [comment]
@ccfish86 我网上找到一个解决方案，不过需要修改源码。[链接](https://segmentfault.com/q/1010000007859368/a-1020000007957257)。
解决方案就是：修改ueditor.all.js中简单上传函数
在图片上传完成后修改loading图的src属性，展示真实图片后，在末尾插入一个空字符串来出发$apply。

**Comment by ghost** [comment]
@ccfish86 @tyua07 https://github.com/HaoChuan9421
