### ISSUE TITLE
我想在点击一个按钮后，调用setContent()方法，应该怎么调用。

### ISSUE THREAD

**Issue by kaeryehaowan** [SilentTiger/vue-ueditor#9]
我现在不知道用哪个对象来调用这个setContent()。你的文档介绍中调用是在，ready事件里调用的。

**Comment by SilentTiger** [comment]
https://github.com/SilentTiger/vue-ueditor/blob/master/src/APP.vue

第14行，取到这个实例之后存储到vue组件的data属性下面，然后你就可以在任何时候调用实例上的方法了
